### ISSUE TITLE
Plan for CRAN release

### ISSUE THREAD

**Issue by sebffischer** [HenrikBengtsson/marshal#10]
Thanks for the work on this useful package! We are currently implementing something similar for the mlr3 ecosystem. Is there a plan for when this package will make it to CRAN so we could potentially build upon it?

**Comment by HenrikBengtsson** [comment]
CRAN ETA is unknown. I think the main problem here is to come up with a stable API, because as soon as we go live, it's really hard to roll back.  I can also imagine rolling out what's stable right now, and then open up more and more as we go.

I'm aware of a few parallel interests on this topic (e.g. mirai is looking into these problems too), so maybe it's worth putting together an informal working group to establish some kind of de-facto standard.

I'm also open to do a call discussing where you are with mlr3 and what your needs are there.

**Comment by sebffischer** [comment]
> I'm also open to do a call discussing where you are with mlr3 and what your needs are there.

Me and some other colleagues would like to discuss this. I could not easily find your contact information (or was not sure which is the "main" address), but you can find my contact information here https://www.slds.stat.uni-muenchen.de/people/fischer/ to continue this discussion and arrange a meeting.
